export const noxieFrames = [
  { name: 'blink', duration: 1 },
  { name: 'bigeyes', duration: 4 },
  { name: 'food', duration: 4 },
  { name: 'indark', duration: 4 },
  { name: 'blink', duration: 1 },
  { name: 'lookdown', duration: 2 },
  { name: 'lookleft', duration: 2 },
  { name: 'lookright', duration: 2 },
  { name: 'blink', duration: 1 },
  { name: 'lookup', duration: 2 },
  { name: 'mouth', duration: 4 },
  { name: 'panic', duration: 4 },
  { name: 'blink', duration: 1 },
  { name: 'tongue', duration: 4 },
  { name: 'litter', duration: 4 },
  { name: 'bow', duration: 5 },
];

export const weatherFrames = [
  { code: '01d', overlay: false },
  { code: '01n', overlay: false },
  { code: '02d', overlay: false },
  { code: '02n', overlay: false },
  { code: '03d', overlay: false },
  { code: '03n', overlay: false },
  { code: '04d', overlay: false },
  { code: '04n', overlay: false },
  { code: '09d', overlay: true },
  { code: '09n', overlay: true },
  { code: '10d', overlay: true },
  { code: '10n', overlay: true },
  { code: '11d', overlay: false },
  { code: '11n', overlay: false },
  { code: '13d', overlay: true },
  { code: '13n', overlay: true },
  { code: '50d', overlay: true },
  { code: '50n', overlay: true },
];
